# Generated by Django 4.2.7 on 2024-02-02 22:58

from django.db import migrations

def add_plan_data(apps, schema_editor):
    Plan = apps.get_model('myapp', 'Plan')
    Plan.objects.create(name="Free", price=0)
    Plan.objects.create(name="Standard", price=10)
    Plan.objects.create(name="Pro", price=25)
    
class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_plan_data),
    ]

